language: ruby
rvm:
- 2.4.10
- 2.7.2
before_script: bundle exec rake db:migrate RAILS_ENV=test
before_install: gem update bundler
cache: bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
